version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.1.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Format and validate
          command: |
            entrypoints=$(git ls-files *.tf | xargs -I{} dirname {} | sort | uniq)

            for dir in ${entrypoints}
            do
              echo "Validating ${dir}..."

              terraform -chdir=${dir} init -backend=false
              terraform -chdir=${dir} fmt -check -diff
              terraform -chdir=${dir} validate
            done
