apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git@github.com:RecrdGroup/kustomize.git//staging/base?ref=1.3.0

components:
  - git@github.com:RecrdGroup/kustomize.git//staging/components/api?ref=1.3.0
  - git@github.com:RecrdGroup/kustomize.git//staging/components/cassandra?ref=1.3.0
  - git@github.com:RecrdGroup/kustomize.git//staging/components/kafka?ref=1.3.0

patches:
  - patch_deployment.yaml
  - patch_ingress.yaml
  - patch_sealedsecret.yaml

namePrefix: congo-

commonLabels:
  app: congo

images:
  - name: app
    newName: 378942204220.dkr.ecr.eu-west-1.amazonaws.com/congo

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - APP_MODE=staging
      - ASTRA_DB_ID=49d61726-2ffe-4dd9-a115-378c2519a13b
      - AWS_REGION=eu-west-1
      - CONTENT_BUCKET=recrd-staging-content
      - CONTENT_BUCKET_HOST_NAME=staging-content.stg.recrd.com
      - KAFKA_GROUP_ID=congo_app
      - UPLOAD_BUCKET=recrd-staging-upload
      - DANUBE_TOKEN_PUBLIC_KEY=/data/jwt/signer.pub
