# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    astra = {
      source  = "datastax/astra"
      version = "~> 2.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "3.70.0"
    }
    tfe = {
      version = "~> 0.27"
    }
  }
}

provider "astra" {
  token = var.astra_token
}

provider "aws" {
  region = "eu-west-1"
}

provider "tfe" {
  token = var.tfe_token
}
