# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "recrd-terraform"
    dynamodb_table = "terraform-lock"
    encrypt        = true
    key            = "users/terraform.tfstate"
    region         = "eu-west-1"
  }
}
